spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coach-assistant
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ente123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties: 
      hibernate: 
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
